// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtANQKnpBs8UChN4X8O5ZDYEf6WmnxE4k',
    appId: '1:1063104742640:web:4574241b5d75fc6e156e35',
    messagingSenderId: '1063104742640',
    projectId: 'money-management-b9fcd',
    authDomain: 'money-management-b9fcd.firebaseapp.com',
    storageBucket: 'money-management-b9fcd.appspot.com',
    measurementId: 'G-GFCT8RWBEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAziCs5Ju1pyuWrpyJMTdQ1IRIfOToHwDc',
    appId: '1:1063104742640:android:b74c16f924a237bc156e35',
    messagingSenderId: '1063104742640',
    projectId: 'money-management-b9fcd',
    storageBucket: 'money-management-b9fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGRir1o1lzNUMDadgI7KUTx7xQt3XMLBs',
    appId: '1:1063104742640:ios:e5f71405b80c02d9156e35',
    messagingSenderId: '1063104742640',
    projectId: 'money-management-b9fcd',
    storageBucket: 'money-management-b9fcd.appspot.com',
    iosBundleId: 'com.example.flutterStock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGRir1o1lzNUMDadgI7KUTx7xQt3XMLBs',
    appId: '1:1063104742640:ios:387f092b1933652e156e35',
    messagingSenderId: '1063104742640',
    projectId: 'money-management-b9fcd',
    storageBucket: 'money-management-b9fcd.appspot.com',
    iosBundleId: 'com.example.flutterStock.RunnerTests',
  );
}
